In [7]:
import numpy as np
from scipy.optimize import minimize


In [8]:
d0 = 1
P0_d0 = -40
gamma = 2.0
R = 50

anchor_nodes = np.array([
    [0, 0],
    [50, 0],
    [0, 50],
    [50, 50]
])

rssi_measurements = np.array([-50, -52, -48, -51])

In [9]:
def estimate_distance(rssi):
    return d0 * 10 ** ((P0_d0 - rssi) / (10 * gamma))

distances = np.array([estimate_distance(rssi) for rssi in rssi_measurements])


In [10]:
def localization_error(un_pos, anchors, distances):
    error = 0
    for i in range(len(anchors)):
        estimated_distance = np.linalg.norm(un_pos - anchors[i])
        error += (estimated_distance - distances[i]) ** 2
    return error

initial_guess = np.array([25, 25])

result = minimize(localization_error, initial_guess, args=(anchor_nodes, distances), method='BFGS')

un_position = result.x

print("Anchor Nodes:")
print(anchor_nodes)
print("Measured RSSI:")
print(rssi_measurements)
print("Estimated Distances:")
print(distances)
print("Estimated UN Position:")
print(un_position)


Anchor Nodes:
[[ 0  0]
 [50  0]
 [ 0 50]
 [50 50]]
Measured RSSI:
[-50 -52 -48 -51]
Estimated Distances:
[3.16227766 3.98107171 2.51188643 3.54813389]
Estimated UN Position:
[24.65587044 25.20117151]
